YUK-14913 Deleting too many devices with Database Editor causes java.lang.NoClassDefFoundError: org/jfree/util/Log  - replaced the incorrect jfree Log class usage with Logger (log4j)