Fixing web-commons Eclipse output path so that it won't collide with command line builds. Should prevent errors like:
SEVERE: Error configuring application listener of class com.cannontech.web.util.CannonContextLoaderListener
java.lang.ClassNotFoundException: com.cannontech.web.util.CannonContextLoaderListener